### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/hoply#17]
- [ ] write an article, take inspiration from "graph based recommendation system python" use it on:
  - [ ] pypi
  - [ ] mathexchange
  - [ ] stackoverflow
- [ ] fuzzy search, take inspiration from https://github.com/seatgeek/fuzzywuzzy
- [ ] submit to https://github.com/jbmusso/awesome-graph
- [ ] graph embedding?
- [ ] graph algorithm?
- [ ] visualization? maybe https://github.com/buzzfeed/pyh3/
- [ ] debug
- [ ] add travis badge
- [ ] add coverage badge
- [ ] improve README
  - [ ] explain that it's easier to install from git since the `Makefile` compiles the required system dependency
  - [ ] add example queries
  - [ ] write full reference documentation

**Comment by amirouche** [comment]
Actually, the current interface doesn't allow to compose layers. See more recent work that would to compose layers https://srfi.schemers.org/srfi-167/ and https://srfi.schemers.org/srfi-168

**Comment by amirouche** [comment]
> The current interface doesn't allow to compose layers.

Done.
